### ISSUE TITLE
Latest release doesn't compile

### ISSUE THREAD

**Issue by bergmark** [BioHaskell/biophd#1]
http://matrix.hackage.haskell.org/package/biophd#GHC-7.8/biophd-0.0.6

**Comment by dfornika** [comment]
Hi Adam,

Thanks for opening the issue.  I hadn't seen that matrix site before, it looks like a great resource.

From what I see in the error message it's a namespace issue.  I'll take a closer look at this as soon as I can.

**Comment by dfornika** [comment]
I think I've solved the issue.  It looks like a couple of source files were missing from the biophd-0.0.6 tar.gz that was uploaded to hackage. I've uploaded biophd-0.0.7 that seems to have all the necessary files.

I'd like to queue a new build on the Hackage Matrix Builder site, but it doesn't seem to accept my hackage user/pass. Can you point me to an explanation on how I register for the builder site and/or associate my account with the biophd package?

**Comment by bergmark** [comment]
I queued it for you, currently only hackage trustees can do this since it's a new project. I think it's a good idea to let anyone at least request a build though.

**Comment by dfornika** [comment]
It looks like biophd-0.0.7 now passes on GHC 7.4-7.8.  Would you mind if I close this issue? It looks like Michael Snoyman has opened an issue addressing the build status on GHC 7.10.

**Comment by bergmark** [comment]
I recommend that you put a `base >= 4.5` lower bound on the project if you don't (intend to) support GHC < 7.4. Then any users  on older GHC's doing `cabal install biophd` will get an older version that works.

**Comment by dfornika** [comment]
Thanks, I've made the change you suggested for biophd-0.0.8.  I'd like to include the fix for issue #2 (ambiguity in time libraries) in that version as well.

**Comment by bergmark** [comment]
Great, thanks! I'll close this then.
